site_name: My Docs
theme:
  name: material
  features: 
    - content.code.copy
    - content.code.select
  palette:
    primary: blue grey
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences